name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install ultralytics
        pip install supervision
        pip install pillow

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "assets;assets" --add-data "yolo_microplastic.pt;." --add-data "../venv/lib/python3.10/site-packages/ultralytics/cfg/default.yaml;ultralytics/cfg" microcheck.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: microcheck
        path: dist/microcheck.exe
